os: linux
arch: amd64
language: java
jdk: openjdk11

install:
  - nvm install 14.17.6
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - wget "https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip"
  - unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
  - sudo ./sam-installation/install

script:
- cd core
- ./gradlew build
- cd ..
- sam validate
- sam build
- sam deploy

#add following environment variables using travis ci ui
#AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION
