os: linux
arch: amd64
language: java
jdk: openjdk11

services:
  - docker

addons:
  sonarcloud:
    organization: "zero-bs"

env:
  - USE_LOCAL_DB=true

install:
  - nvm install 14.17.6
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - wget "https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip"
  - unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
  - sudo ./sam-installation/install
  - docker run -dp 8000:8000 amazon/dynamodb-local

script:
  - cd authorizer
  - sonar-scanner
  - cd ../core
  - ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN
  - sleep 10
  - qualityGate=$(curl --location --request GET 'https://sonarcloud.io/api/qualitygates/project_status?branch=main&projectKey=Zero-BS_polla-backend' | jq -r '.projectStatus.status')
  - if [ $qualityGate != 'OK' ]; then exit 1; fi
  - cd ..
  - sam validate

after_success:
  - travis_wait sam build
  - sam deploy --parameter-overrides ParameterKey=AndroidGoogleClientId,ParameterValue=$ANDROID_GOOGLE_CLIENT_ID ParameterKey=WebGoogleClientId,ParameterValue=$WEB_GOOGLE_CLIENT_ID

after_failure:
  - travis_terminate 1

#add following environment variables using travis ci ui
#AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION, ANDROID_GOOGLE_CLIENT_ID, WEB_GOOGLE_CLIENT_ID, SONAR_TOKEN