version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "polla-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ufqsguoffqsv"
s3_prefix = "polla-app"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
